{{- if eq .Values.architecture "sentinel" }}
{{- if .Values.sentinel.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "renderAnnotations" (dict "additionalAnnotations" .Values.sentinel.service.annotations "context" $) | indent 2 }}
  {{- include "renderLabels" (dict "component" "sentinel" "context" $) | indent 2 }}
  name: {{ include "fullName" (dict "suffix" "sentinel" "context" $) }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "renderValues" (dict "omitKeys" (list "enabled" "annotations" "nodePorts" "ports" "selector") "values" .Values.sentinel.service) | indent 2 }}
  ports: {{- range $key, $value := .Values.sentinel.service.ports }}
    {{- if and $key (coalesce $value (get $.Values.containerPorts $key)) }}
    - name: {{ $key }}
      {{- if has $.Values.sentinel.service.type (list "LoadBalancer" "NodePort") }}
      {{- if not (empty (get $.Values.sentinel.service.nodePorts $key)) }}
      nodePort: {{ get $.Values.sentinel.service.nodePorts $key }}
      {{- end }}
      {{- end }}
      port: {{ coalesce $value (get $.Values.containerPorts $key) }}
      {{- if get $.Values.containerPorts $key }}
      targetPort: {{ $key }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector: {{- include "matchLabels" (dict "additionalLabels" .Values.sentinel.podTemplates.labels "component" "sentinel" "context" $) | nindent 4 }}
{{- end }}
{{- end }}
