{{- if eq (include "templateToBoolean" (dict "template" .Values.configMap.enabled "context" $)) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "renderAnnotations" . | indent 2 }}
  {{- include "renderLabels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "fullName" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- range $configMapName, $configMapValue := .Values.configMap }}
  {{- if and $configMapName (ne $configMapName "enabled") $configMapValue }}
  {{ tpl $configMapName $ }}: |
    {{- tpl $configMapValue $ | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
