{{- if (eq (include "templateToBoolean" (dict "template" .Values.secret.enabled "context" $)) "true") }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "renderAnnotations" . | indent 2 }}
  {{- include "renderLabels" (dict "component" "main" "context" $) | indent 2 }}
  name: {{ include "fullName" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- range $secretName, $secretValue := .Values.secret }}
  {{- if and $secretName (ne $secretName "enabled") $secretValue }}
  {{ tpl $secretName $ }}: {{ include "lookupSecret" (dict "default" (tpl $secretValue $) "key" (tpl $secretName $) "context" $) }}
  {{- end }}
  {{- end }}
{{- end }}
