{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "renderAnnotations" (dict "additionalAnnotations" .Values.serviceAccount.annotations "context" $) | indent 2 }}
  {{- include "renderLabels" (dict "additionalLabels" .Values.serviceAccount.labels "context" $) | indent 2 }}
  name: {{ include "serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- include "renderValues" (dict "omitKeys" (list "enabled" "annotations" "labels" "name") "values" .Values.serviceAccount) | indent 0 }}
{{- end }}
